export interface TemplateMetadata {
  name: string;
  templateCode: string;
  filePath: string; // Path to .hbs file relative to html-templates/
  channel: 'email' | 'sms' | 'fcm' | 'whatsapp';
  category: string;
  subject?: string;
  variables: Record<string, string>; // variable name -> type/description
  language: string;
  description: string;
  tags: string[];
}

export const templateMetadata: TemplateMetadata[] = [
  // ==================== AUTHENTICATION TEMPLATES ====================
  {
    name: 'Welcome Email',
    templateCode: 'WELCOME_EMAIL',
    filePath: 'transactional/authentication/welcome-email.hbs',
    channel: 'email',
    category: 'AUTHENTICATION',
    subject: 'Welcome to {{companyName}}!',
    variables: {
      firstName: 'string - User first name',
      lastName: 'string - User last name',
      email: 'string - User email address',
      companyName: 'string - Company name',
      loginUrl: 'string - Login page URL',
    },
    language: 'en',
    description: 'Welcome new users after registration',
    tags: ['authentication', 'welcome', 'onboarding'],
  },
  {
    name: 'Email Verification',
    templateCode: 'EMAIL_VERIFICATION',
    filePath: 'transactional/authentication/email-verification.hbs',
    channel: 'email',
    category: 'AUTHENTICATION',
    subject: 'Verify Your Email Address',
    variables: {
      firstName: 'string - User first name',
      verificationCode: 'string - 6-digit verification code',
      verificationLink: 'string - Verification URL',
      expiryMinutes: 'number - Code expiry in minutes',
      companyName: 'string - Company name',
    },
    language: 'en',
    description: 'Email verification with code and link',
    tags: ['authentication', 'verification', 'security'],
  },
  {
    name: 'Password Reset',
    templateCode: 'PASSWORD_RESET',
    filePath: 'transactional/authentication/password-reset.hbs',
    channel: 'email',
    category: 'AUTHENTICATION',
    subject: 'Reset Your Password',
    variables: {
      firstName: 'string - User first name',
      resetLink: 'string - Password reset URL',
      expiryHours: 'number - Link expiry in hours',
      companyName: 'string - Company name',
    },
    language: 'en',
    description: 'Password reset request with secure link',
    tags: ['authentication', 'password', 'security'],
  },
  {
    name: 'Password Changed',
    templateCode: 'PASSWORD_CHANGED',
    filePath: 'transactional/authentication/password-changed.hbs',
    channel: 'email',
    category: 'AUTHENTICATION',
    subject: 'Your Password Has Been Changed',
    variables: {
      firstName: 'string - User first name',
      changeTime: 'string - Time of password change',
      ipAddress: 'string - IP address of change',
      supportUrl: 'string - Support page URL',
      companyName: 'string - Company name',
    },
    language: 'en',
    description: 'Confirmation of password change',
    tags: ['authentication', 'password', 'security'],
  },
  {
    name: 'Two-Factor Authentication',
    templateCode: 'TWO_FACTOR_AUTH',
    filePath: 'transactional/authentication/two-factor-auth.hbs',
    channel: 'email',
    category: 'AUTHENTICATION',
    subject: 'Your Authentication Code',
    variables: {
      firstName: 'string - User first name',
      code: 'string - 6-digit 2FA code',
      expiryMinutes: 'number - Code expiry in minutes',
      companyName: 'string - Company name',
    },
    language: 'en',
    description: '2FA code delivery',
    tags: ['authentication', '2fa', 'security'],
  },
  {
    name: 'Two-Factor Enabled',
    templateCode: 'TWO_FACTOR_ENABLED',
    filePath: 'transactional/authentication/two-factor-enabled.hbs',
    channel: 'email',
    category: 'AUTHENTICATION',
    subject: 'Two-Factor Authentication Enabled',
    variables: {
      firstName: 'string - User first name',
      enableTime: 'string - Time 2FA was enabled',
      companyName: 'string - Company name',
    },
    language: 'en',
    description: '2FA setup confirmation',
    tags: ['authentication', '2fa', 'security'],
  },
  {
    name: 'Login Notification',
    templateCode: 'LOGIN_NOTIFICATION',
    filePath: 'transactional/authentication/login-notification.hbs',
    channel: 'email',
    category: 'AUTHENTICATION',
    subject: 'New Login to Your Account',
    variables: {
      firstName: 'string - User first name',
      loginTime: 'string - Time of login',
      device: 'string - Device used',
      location: 'string - Login location',
      ipAddress: 'string - IP address',
      securityUrl: 'string - Security settings URL',
      companyName: 'string - Company name',
    },
    language: 'en',
    description: 'New device/location login alert',
    tags: ['authentication', 'security', 'alert'],
  },

  // ==================== ACCOUNT MANAGEMENT TEMPLATES ====================
  {
    name: 'Account Activated',
    templateCode: 'ACCOUNT_ACTIVATED',
    filePath: 'transactional/account/account-activated.hbs',
    channel: 'email',
    category: 'ACCOUNT',
    subject: 'Your Account is Active',
    variables: {
      firstName: 'string - User first name',
      loginUrl: 'string - Login page URL',
      companyName: 'string - Company name',
    },
    language: 'en',
    description: 'Account activation confirmation',
    tags: ['account', 'activation'],
  },
  {
    name: 'Account Suspended',
    templateCode: 'ACCOUNT_SUSPENDED',
    filePath: 'transactional/account/account-suspended.hbs',
    channel: 'email',
    category: 'ACCOUNT',
    subject: 'Your Account Has Been Suspended',
    variables: {
      firstName: 'string - User first name',
      reason: 'string - Suspension reason',
      supportUrl: 'string - Support page URL',
      companyName: 'string - Company name',
    },
    language: 'en',
    description: 'Account suspension notice',
    tags: ['account', 'suspension', 'alert'],
  },
  {
    name: 'Account Deleted',
    templateCode: 'ACCOUNT_DELETED',
    filePath: 'transactional/account/account-deleted.hbs',
    channel: 'email',
    category: 'ACCOUNT',
    subject: 'Your Account Has Been Deleted',
    variables: {
      firstName: 'string - User first name',
      deletionDate: 'string - Account deletion date',
      companyName: 'string - Company name',
    },
    language: 'en',
    description: 'Account deletion confirmation',
    tags: ['account', 'deletion'],
  },
  {
    name: 'Profile Updated',
    templateCode: 'PROFILE_UPDATED',
    filePath: 'transactional/account/profile-updated.hbs',
    channel: 'email',
    category: 'ACCOUNT',
    subject: 'Your Profile Has Been Updated',
    variables: {
      firstName: 'string - User first name',
      updateTime: 'string - Time of update',
      changedFields: 'string - List of changed fields',
      profileUrl: 'string - Profile page URL',
      companyName: 'string - Company name',
    },
    language: 'en',
    description: 'Profile changes confirmation',
    tags: ['account', 'profile', 'update'],
  },
  {
    name: 'Settings Changed',
    templateCode: 'SETTINGS_CHANGED',
    filePath: 'transactional/account/settings-changed.hbs',
    channel: 'email',
    category: 'ACCOUNT',
    subject: 'Your Settings Have Been Changed',
    variables: {
      firstName: 'string - User first name',
      changeTime: 'string - Time of change',
      changedSettings: 'string - List of changed settings',
      settingsUrl: 'string - Settings page URL',
      companyName: 'string - Company name',
    },
    language: 'en',
    description: 'Settings modification notice',
    tags: ['account', 'settings', 'update'],
  },
  {
    name: 'Email Changed',
    templateCode: 'EMAIL_CHANGED',
    filePath: 'transactional/account/email-changed.hbs',
    channel: 'email',
    category: 'ACCOUNT',
    subject: 'Your Email Address Has Been Changed',
    variables: {
      firstName: 'string - User first name',
      oldEmail: 'string - Previous email address',
      newEmail: 'string - New email address',
      changeTime: 'string - Time of change',
      supportUrl: 'string - Support page URL',
      companyName: 'string - Company name',
    },
    language: 'en',
    description: 'Email address change verification',
    tags: ['account', 'email', 'security'],
  },
  {
    name: 'Phone Changed',
    templateCode: 'PHONE_CHANGED',
    filePath: 'transactional/account/phone-changed.hbs',
    channel: 'email',
    category: 'ACCOUNT',
    subject: 'Your Phone Number Has Been Changed',
    variables: {
      firstName: 'string - User first name',
      oldPhone: 'string - Previous phone number',
      newPhone: 'string - New phone number',
      changeTime: 'string - Time of change',
      supportUrl: 'string - Support page URL',
      companyName: 'string - Company name',
    },
    language: 'en',
    description: 'Phone number change verification',
    tags: ['account', 'phone', 'security'],
  },

  // ==================== SYSTEM NOTIFICATION TEMPLATES ====================
  {
    name: 'System Alert',
    templateCode: 'SYSTEM_ALERT',
    filePath: 'transactional/notifications/system-alert.hbs',
    channel: 'email',
    category: 'SYSTEM',
    subject: 'System Alert: {{alertTitle}}',
    variables: {
      alertTitle: 'string - Alert title',
      alertMessage: 'string - Alert message',
      severity: 'string - Alert severity (low/medium/high/critical)',
      actionUrl: 'string - Action URL if applicable',
      companyName: 'string - Company name',
    },
    language: 'en',
    description: 'Critical system alerts',
    tags: ['system', 'alert', 'notification'],
  },
  {
    name: 'Maintenance Notice',
    templateCode: 'MAINTENANCE_NOTICE',
    filePath: 'transactional/notifications/maintenance-notice.hbs',
    channel: 'email',
    category: 'SYSTEM',
    subject: 'Scheduled Maintenance Notice',
    variables: {
      maintenanceDate: 'string - Scheduled maintenance date',
      maintenanceTime: 'string - Scheduled maintenance time',
      duration: 'string - Expected duration',
      impactDescription: 'string - Impact description',
      companyName: 'string - Company name',
    },
    language: 'en',
    description: 'Scheduled maintenance notifications',
    tags: ['system', 'maintenance', 'notification'],
  },
  {
    name: 'Security Alert',
    templateCode: 'SECURITY_ALERT',
    filePath: 'transactional/notifications/security-alert.hbs',
    channel: 'email',
    category: 'SECURITY',
    subject: 'Security Alert: {{alertTitle}}',
    variables: {
      alertTitle: 'string - Security alert title',
      alertMessage: 'string - Security alert message',
      actionRequired: 'string - Required action',
      actionUrl: 'string - Action URL',
      supportUrl: 'string - Support page URL',
      companyName: 'string - Company name',
    },
    language: 'en',
    description: 'Security-related warnings',
    tags: ['security', 'alert', 'notification'],
  },
  {
    name: 'Payment Reminder',
    templateCode: 'PAYMENT_REMINDER',
    filePath: 'transactional/notifications/payment-reminder.hbs',
    channel: 'email',
    category: 'BILLING',
    subject: 'Payment Due Reminder',
    variables: {
      firstName: 'string - User first name',
      amount: 'number - Payment amount',
      dueDate: 'string - Payment due date',
      invoiceUrl: 'string - Invoice URL',
      paymentUrl: 'string - Payment page URL',
      companyName: 'string - Company name',
    },
    language: 'en',
    description: 'Payment due reminders',
    tags: ['billing', 'payment', 'reminder'],
  },
  {
    name: 'Subscription Expiring',
    templateCode: 'SUBSCRIPTION_EXPIRING',
    filePath: 'transactional/notifications/subscription-expiring.hbs',
    channel: 'email',
    category: 'BILLING',
    subject: 'Your Subscription is Expiring Soon',
    variables: {
      firstName: 'string - User first name',
      planName: 'string - Subscription plan name',
      expiryDate: 'string - Subscription expiry date',
      renewUrl: 'string - Renewal page URL',
      companyName: 'string - Company name',
    },
    language: 'en',
    description: 'Subscription expiration notice',
    tags: ['billing', 'subscription', 'reminder'],
  },
  {
    name: 'Task Reminder',
    templateCode: 'TASK_REMINDER',
    filePath: 'transactional/notifications/task-reminder.hbs',
    channel: 'email',
    category: 'PRODUCTIVITY',
    subject: 'Task Reminder: {{taskTitle}}',
    variables: {
      firstName: 'string - User first name',
      taskTitle: 'string - Task title',
      taskDescription: 'string - Task description',
      dueDate: 'string - Task due date',
      taskUrl: 'string - Task URL',
      companyName: 'string - Company name',
    },
    language: 'en',
    description: 'Task/deadline reminders',
    tags: ['productivity', 'task', 'reminder'],
  },

  // ==================== MARKETING CAMPAIGN TEMPLATES ====================
  {
    name: 'Newsletter Standard',
    templateCode: 'NEWSLETTER_STANDARD',
    filePath: 'marketing/campaigns/newsletter-standard.hbs',
    channel: 'email',
    category: 'MARKETING',
    subject: '{{newsletterTitle}}',
    variables: {
      firstName: 'string - User first name',
      newsletterTitle: 'string - Newsletter title',
      heroImage: 'string - Hero image URL',
      mainContent: 'string - Main newsletter content',
      ctaText: 'string - Call to action text',
      ctaUrl: 'string - Call to action URL',
      unsubscribeUrl: 'string - Unsubscribe URL',
      companyName: 'string - Company name',
    },
    language: 'en',
    description: 'Standard newsletter layout',
    tags: ['marketing', 'newsletter', 'campaign'],
  },
  {
    name: 'Newsletter Digest',
    templateCode: 'NEWSLETTER_DIGEST',
    filePath: 'marketing/campaigns/newsletter-digest.hbs',
    channel: 'email',
    category: 'MARKETING',
    subject: '{{digestTitle}} - {{period}}',
    variables: {
      firstName: 'string - User first name',
      digestTitle: 'string - Digest title',
      period: 'string - Time period (weekly/monthly)',
      articles: 'array - Array of article objects',
      unsubscribeUrl: 'string - Unsubscribe URL',
      companyName: 'string - Company name',
    },
    language: 'en',
    description: 'Digest/roundup format newsletter',
    tags: ['marketing', 'newsletter', 'digest'],
  },
  {
    name: 'Product Announcement',
    templateCode: 'PRODUCT_ANNOUNCEMENT',
    filePath: 'marketing/campaigns/product-announcement.hbs',
    channel: 'email',
    category: 'MARKETING',
    subject: 'Introducing {{productName}}',
    variables: {
      firstName: 'string - User first name',
      productName: 'string - Product name',
      productDescription: 'string - Product description',
      productImage: 'string - Product image URL',
      launchDate: 'string - Launch date',
      ctaText: 'string - Call to action text',
      ctaUrl: 'string - Call to action URL',
      unsubscribeUrl: 'string - Unsubscribe URL',
      companyName: 'string - Company name',
    },
    language: 'en',
    description: 'New product/feature launch announcement',
    tags: ['marketing', 'product', 'announcement'],
  },
  {
    name: 'Product Update',
    templateCode: 'PRODUCT_UPDATE',
    filePath: 'marketing/campaigns/product-update.hbs',
    channel: 'email',
    category: 'MARKETING',
    subject: 'New Updates to {{productName}}',
    variables: {
      firstName: 'string - User first name',
      productName: 'string - Product name',
      updates: 'array - Array of update items',
      ctaText: 'string - Call to action text',
      ctaUrl: 'string - Call to action URL',
      unsubscribeUrl: 'string - Unsubscribe URL',
      companyName: 'string - Company name',
    },
    language: 'en',
    description: 'Feature updates and improvements',
    tags: ['marketing', 'product', 'update'],
  },
  {
    name: 'Company News',
    templateCode: 'COMPANY_NEWS',
    filePath: 'marketing/campaigns/company-news.hbs',
    channel: 'email',
    category: 'MARKETING',
    subject: '{{newsTitle}}',
    variables: {
      firstName: 'string - User first name',
      newsTitle: 'string - News title',
      newsContent: 'string - News content',
      newsImage: 'string - News image URL',
      readMoreUrl: 'string - Read more URL',
      unsubscribeUrl: 'string - Unsubscribe URL',
      companyName: 'string - Company name',
    },
    language: 'en',
    description: 'Company announcements and news',
    tags: ['marketing', 'company', 'news'],
  },
  {
    name: 'Blog Digest',
    templateCode: 'BLOG_DIGEST',
    filePath: 'marketing/campaigns/blog-digest.hbs',
    channel: 'email',
    category: 'MARKETING',
    subject: 'Latest from Our Blog',
    variables: {
      firstName: 'string - User first name',
      posts: 'array - Array of blog post objects',
      unsubscribeUrl: 'string - Unsubscribe URL',
      companyName: 'string - Company name',
    },
    language: 'en',
    description: 'Blog post roundup',
    tags: ['marketing', 'blog', 'digest'],
  },

  // ==================== ENGAGEMENT TEMPLATES ====================
  {
    name: 'Welcome Series 1',
    templateCode: 'WELCOME_SERIES_1',
    filePath: 'marketing/engagement/welcome-series-1.hbs',
    channel: 'email',
    category: 'ENGAGEMENT',
    subject: 'Welcome to {{companyName}} - Let\'s Get Started!',
    variables: {
      firstName: 'string - User first name',
      step1Title: 'string - First step title',
      step1Description: 'string - First step description',
      step1Url: 'string - First step URL',
      companyName: 'string - Company name',
      unsubscribeUrl: 'string - Unsubscribe URL',
    },
    language: 'en',
    description: 'First onboarding email',
    tags: ['engagement', 'onboarding', 'welcome'],
  },
  {
    name: 'Welcome Series 2',
    templateCode: 'WELCOME_SERIES_2',
    filePath: 'marketing/engagement/welcome-series-2.hbs',
    channel: 'email',
    category: 'ENGAGEMENT',
    subject: 'Getting More From {{companyName}}',
    variables: {
      firstName: 'string - User first name',
      feature1: 'string - Feature 1 description',
      feature2: 'string - Feature 2 description',
      feature3: 'string - Feature 3 description',
      exploreUrl: 'string - Explore URL',
      companyName: 'string - Company name',
      unsubscribeUrl: 'string - Unsubscribe URL',
    },
    language: 'en',
    description: 'Second onboarding email',
    tags: ['engagement', 'onboarding', 'features'],
  },
  {
    name: 'Welcome Series 3',
    templateCode: 'WELCOME_SERIES_3',
    filePath: 'marketing/engagement/welcome-series-3.hbs',
    channel: 'email',
    category: 'ENGAGEMENT',
    subject: 'Tips for Success with {{companyName}}',
    variables: {
      firstName: 'string - User first name',
      tip1: 'string - Tip 1',
      tip2: 'string - Tip 2',
      tip3: 'string - Tip 3',
      resourcesUrl: 'string - Resources URL',
      companyName: 'string - Company name',
      unsubscribeUrl: 'string - Unsubscribe URL',
    },
    language: 'en',
    description: 'Third onboarding email',
    tags: ['engagement', 'onboarding', 'tips'],
  },
  {
    name: 'Re-engagement',
    templateCode: 'RE_ENGAGEMENT',
    filePath: 'marketing/engagement/re-engagement.hbs',
    channel: 'email',
    category: 'ENGAGEMENT',
    subject: 'We Miss You at {{companyName}}',
    variables: {
      firstName: 'string - User first name',
      lastActive: 'string - Last active date',
      newFeatures: 'array - Array of new features',
      incentive: 'string - Re-engagement incentive',
      returnUrl: 'string - Return URL',
      companyName: 'string - Company name',
      unsubscribeUrl: 'string - Unsubscribe URL',
    },
    language: 'en',
    description: 'Win back inactive users',
    tags: ['engagement', 're-engagement', 'retention'],
  },
  {
    name: 'Referral Invite',
    templateCode: 'REFERRAL_INVITE',
    filePath: 'marketing/engagement/referral-invite.hbs',
    channel: 'email',
    category: 'ENGAGEMENT',
    subject: 'Share {{companyName}} and Get Rewarded',
    variables: {
      firstName: 'string - User first name',
      referralCode: 'string - Referral code',
      referralUrl: 'string - Referral URL',
      reward: 'string - Referral reward description',
      companyName: 'string - Company name',
      unsubscribeUrl: 'string - Unsubscribe URL',
    },
    language: 'en',
    description: 'Referral program invitation',
    tags: ['engagement', 'referral', 'growth'],
  },
  {
    name: 'Feedback Request',
    templateCode: 'FEEDBACK_REQUEST',
    filePath: 'marketing/engagement/feedback-request.hbs',
    channel: 'email',
    category: 'ENGAGEMENT',
    subject: 'We\'d Love Your Feedback',
    variables: {
      firstName: 'string - User first name',
      surveyUrl: 'string - Survey URL',
      estimatedTime: 'string - Estimated completion time',
      incentive: 'string - Survey incentive (optional)',
      companyName: 'string - Company name',
      unsubscribeUrl: 'string - Unsubscribe URL',
    },
    language: 'en',
    description: 'Survey/feedback request',
    tags: ['engagement', 'feedback', 'survey'],
  },
  {
    name: 'Review Request',
    templateCode: 'REVIEW_REQUEST',
    filePath: 'marketing/engagement/review-request.hbs',
    channel: 'email',
    category: 'ENGAGEMENT',
    subject: 'How Are We Doing?',
    variables: {
      firstName: 'string - User first name',
      productName: 'string - Product/service name',
      reviewUrl: 'string - Review URL',
      companyName: 'string - Company name',
      unsubscribeUrl: 'string - Unsubscribe URL',
    },
    language: 'en',
    description: 'Product/service review request',
    tags: ['engagement', 'review', 'feedback'],
  },
  {
    name: 'User Milestone',
    templateCode: 'USER_MILESTONE',
    filePath: 'marketing/engagement/user-milestone.hbs',
    channel: 'email',
    category: 'ENGAGEMENT',
    subject: 'Congratulations on Your {{milestone}}!',
    variables: {
      firstName: 'string - User first name',
      milestone: 'string - Milestone achieved',
      milestoneDescription: 'string - Milestone description',
      stats: 'array - Array of user stats',
      shareUrl: 'string - Share URL (optional)',
      companyName: 'string - Company name',
      unsubscribeUrl: 'string - Unsubscribe URL',
    },
    language: 'en',
    description: 'Achievement/milestone celebration',
    tags: ['engagement', 'milestone', 'celebration'],
  },

  // ==================== PROMOTIONAL TEMPLATES ====================
  {
    name: 'Special Offer',
    templateCode: 'SPECIAL_OFFER',
    filePath: 'marketing/promotional/special-offer.hbs',
    channel: 'email',
    category: 'PROMOTIONAL',
    subject: 'Special Offer: {{offerTitle}}',
    variables: {
      firstName: 'string - User first name',
      offerTitle: 'string - Offer title',
      offerDescription: 'string - Offer description',
      discount: 'string - Discount amount/percentage',
      expiryDate: 'string - Offer expiry date',
      ctaText: 'string - Call to action text',
      ctaUrl: 'string - Call to action URL',
      companyName: 'string - Company name',
      unsubscribeUrl: 'string - Unsubscribe URL',
    },
    language: 'en',
    description: 'Limited time offers',
    tags: ['promotional', 'offer', 'discount'],
  },
  {
    name: 'Discount Code',
    templateCode: 'DISCOUNT_CODE',
    filePath: 'marketing/promotional/discount-code.hbs',
    channel: 'email',
    category: 'PROMOTIONAL',
    subject: 'Your Exclusive Discount Code',
    variables: {
      firstName: 'string - User first name',
      discountCode: 'string - Discount code',
      discountAmount: 'string - Discount amount/percentage',
      expiryDate: 'string - Code expiry date',
      ctaUrl: 'string - Shop URL',
      companyName: 'string - Company name',
      unsubscribeUrl: 'string - Unsubscribe URL',
    },
    language: 'en',
    description: 'Discount code delivery',
    tags: ['promotional', 'discount', 'code'],
  },
  {
    name: 'Seasonal Sale',
    templateCode: 'SEASONAL_SALE',
    filePath: 'marketing/promotional/seasonal-sale.hbs',
    channel: 'email',
    category: 'PROMOTIONAL',
    subject: '{{season}} Sale - Up to {{discount}}% Off',
    variables: {
      firstName: 'string - User first name',
      season: 'string - Season name',
      discount: 'string - Maximum discount percentage',
      saleDescription: 'string - Sale description',
      startDate: 'string - Sale start date',
      endDate: 'string - Sale end date',
      shopUrl: 'string - Shop URL',
      companyName: 'string - Company name',
      unsubscribeUrl: 'string - Unsubscribe URL',
    },
    language: 'en',
    description: 'Holiday/seasonal promotions',
    tags: ['promotional', 'sale', 'seasonal'],
  },
  {
    name: 'Flash Sale',
    templateCode: 'FLASH_SALE',
    filePath: 'marketing/promotional/flash-sale.hbs',
    channel: 'email',
    category: 'PROMOTIONAL',
    subject: '⚡ Flash Sale: {{discount}}% Off - Ends Soon!',
    variables: {
      firstName: 'string - User first name',
      discount: 'string - Discount percentage',
      endTime: 'string - Sale end time',
      productHighlights: 'array - Featured products',
      shopUrl: 'string - Shop URL',
      companyName: 'string - Company name',
      unsubscribeUrl: 'string - Unsubscribe URL',
    },
    language: 'en',
    description: 'Urgent flash sales',
    tags: ['promotional', 'sale', 'urgent'],
  },
  {
    name: 'Event Invitation',
    templateCode: 'EVENT_INVITATION',
    filePath: 'marketing/promotional/event-invitation.hbs',
    channel: 'email',
    category: 'PROMOTIONAL',
    subject: 'You\'re Invited: {{eventName}}',
    variables: {
      firstName: 'string - User first name',
      eventName: 'string - Event name',
      eventDescription: 'string - Event description',
      eventDate: 'string - Event date',
      eventTime: 'string - Event time',
      eventLocation: 'string - Event location',
      rsvpUrl: 'string - RSVP URL',
      companyName: 'string - Company name',
      unsubscribeUrl: 'string - Unsubscribe URL',
    },
    language: 'en',
    description: 'Event invitations',
    tags: ['promotional', 'event', 'invitation'],
  },
  {
    name: 'Webinar Invitation',
    templateCode: 'WEBINAR_INVITATION',
    filePath: 'marketing/promotional/webinar-invitation.hbs',
    channel: 'email',
    category: 'PROMOTIONAL',
    subject: 'Join Our Webinar: {{webinarTitle}}',
    variables: {
      firstName: 'string - User first name',
      webinarTitle: 'string - Webinar title',
      webinarDescription: 'string - Webinar description',
      speaker: 'string - Speaker name',
      speakerTitle: 'string - Speaker title',
      date: 'string - Webinar date',
      time: 'string - Webinar time',
      registerUrl: 'string - Registration URL',
      companyName: 'string - Company name',
      unsubscribeUrl: 'string - Unsubscribe URL',
    },
    language: 'en',
    description: 'Webinar registration invitation',
    tags: ['promotional', 'webinar', 'education'],
  },
  {
    name: 'Abandoned Cart',
    templateCode: 'ABANDONED_CART',
    filePath: 'marketing/promotional/abandoned-cart.hbs',
    channel: 'email',
    category: 'PROMOTIONAL',
    subject: 'You Left Something Behind...',
    variables: {
      firstName: 'string - User first name',
      cartItems: 'array - Array of cart item objects',
      cartTotal: 'number - Cart total amount',
      cartUrl: 'string - Cart URL',
      incentive: 'string - Incentive to complete purchase (optional)',
      companyName: 'string - Company name',
      unsubscribeUrl: 'string - Unsubscribe URL',
    },
    language: 'en',
    description: 'Cart abandonment recovery',
    tags: ['promotional', 'cart', 'recovery'],
  },

  // ==================== EDUCATIONAL TEMPLATES ====================
  {
    name: 'Tips and Tricks',
    templateCode: 'TIPS_AND_TRICKS',
    filePath: 'marketing/educational/tips-and-tricks.hbs',
    channel: 'email',
    category: 'EDUCATIONAL',
    subject: '{{tipsCount}} Tips to {{goalDescription}}',
    variables: {
      firstName: 'string - User first name',
      tipsCount: 'number - Number of tips',
      goalDescription: 'string - Goal description',
      tips: 'array - Array of tip objects',
      learnMoreUrl: 'string - Learn more URL',
      companyName: 'string - Company name',
      unsubscribeUrl: 'string - Unsubscribe URL',
    },
    language: 'en',
    description: 'Tips series for users',
    tags: ['educational', 'tips', 'learning'],
  },
  {
    name: 'How-To Guide',
    templateCode: 'HOW_TO_GUIDE',
    filePath: 'marketing/educational/how-to-guide.hbs',
    channel: 'email',
    category: 'EDUCATIONAL',
    subject: 'How to {{guideTitle}}',
    variables: {
      firstName: 'string - User first name',
      guideTitle: 'string - Guide title',
      introduction: 'string - Guide introduction',
      steps: 'array - Array of step objects',
      conclusionUrl: 'string - Full guide URL',
      companyName: 'string - Company name',
      unsubscribeUrl: 'string - Unsubscribe URL',
    },
    language: 'en',
    description: 'Step-by-step guides',
    tags: ['educational', 'guide', 'tutorial'],
  },
  {
    name: 'Best Practices',
    templateCode: 'BEST_PRACTICES',
    filePath: 'marketing/educational/best-practices.hbs',
    channel: 'email',
    category: 'EDUCATIONAL',
    subject: 'Best Practices for {{topic}}',
    variables: {
      firstName: 'string - User first name',
      topic: 'string - Topic name',
      introduction: 'string - Introduction',
      practices: 'array - Array of best practice objects',
      resourcesUrl: 'string - Resources URL',
      companyName: 'string - Company name',
      unsubscribeUrl: 'string - Unsubscribe URL',
    },
    language: 'en',
    description: 'Best practices content',
    tags: ['educational', 'best-practices', 'learning'],
  },
  {
    name: 'Case Study',
    templateCode: 'CASE_STUDY',
    filePath: 'marketing/educational/case-study.hbs',
    channel: 'email',
    category: 'EDUCATIONAL',
    subject: 'Case Study: {{customerName}}',
    variables: {
      firstName: 'string - User first name',
      customerName: 'string - Customer name',
      challenge: 'string - Customer challenge',
      solution: 'string - Solution provided',
      results: 'array - Array of result metrics',
      readMoreUrl: 'string - Full case study URL',
      companyName: 'string - Company name',
      unsubscribeUrl: 'string - Unsubscribe URL',
    },
    language: 'en',
    description: 'Customer success stories',
    tags: ['educational', 'case-study', 'success'],
  },
  {
    name: 'Resource Roundup',
    templateCode: 'RESOURCE_ROUNDUP',
    filePath: 'marketing/educational/resource-roundup.hbs',
    channel: 'email',
    category: 'EDUCATIONAL',
    subject: 'Resources for {{topic}}',
    variables: {
      firstName: 'string - User first name',
      topic: 'string - Topic name',
      resources: 'array - Array of resource objects',
      moreResourcesUrl: 'string - More resources URL',
      companyName: 'string - Company name',
      unsubscribeUrl: 'string - Unsubscribe URL',
    },
    language: 'en',
    description: 'Resource collections',
    tags: ['educational', 'resources', 'learning'],
  },
];
